### ISSUE TITLE
Failed to build within Ubuntu 20.04  lldb 10.0 & cmake 3.16.3

### ISSUE THREAD

**Issue by dcnoway** [lldb-tools/lldb-mi#50]
After cloned the repository, the command 'cmake .' raised a error illustrated below.

![Untitled](https://user-images.githubusercontent.com/46963698/83118838-7947a880-a101-11ea-9a14-8c95eede7ac8.png)

Environment:
Ubuntu 20.04 focal on WSL2
lldb 10.0  installed by apt install 
clang 10.0 installed by apt install
cmake 3.16.3 installed by apt install

**Comment by tkrasnukha** [comment]
Please, provide us with more details about your LLDB installation. Where is it located? Does it contain "lldb" or "liblldb" static or shared libraries?

**Comment by mati865** [comment]
You have to install `liblldb-dev` package.

**Comment by lijgame** [comment]
I ran into same situation.
I have `liblldb-10-dev` installed properly.

It turns out because I have both llvm-9 and llvm-10 installed on my Ubuntu 20.04.
llvm-mi will use llvm-9's include path unfortunately.
After remove `libllvm9` and  `llvm-9`, project can build successfully.

If you don't want to uninstall llvm9, I think you can manually set the path.

**Comment by victorromeo** [comment]
> You have to install `liblldb-dev` package.

This worked for me.
